language: php

sudo: false

services: [rabbitmq]

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
    - cmake
    - rabbitmq-server

env:
    global:
        - LIBRABBITMQ_VERSION=v0.8.0
        - SYMFONY_DEPRECATIONS_HELPER="weak" # Required as latest swarrot 3.x version will always trigger a deprecation

matrix:
  fast_finish: true
  include:
    - php: 8.0
    - php: 7.4

    # Tests with latest librabbitmq version
    - php: 8.0
      env: LIBRABBITMQ_VERSION="master"
      dist: focal

    # Test with lowest versions
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest --prefer-stable" # See https://github.com/symfony/symfony/issues/22515

before_install:
  - sudo ./Tests/bin/install_rabbitmq-c.sh
  - ./Tests/bin/install_php-amqp.sh

install:
  - composer update --prefer-dist --no-progress --no-suggest $COMPOSER_FLAGS --ansi

before_script:
  - sh -c "sudo ./Tests/bin/prepare_rabbit.sh"

script: vendor/bin/phpunit
